### ISSUE TITLE
Order parent connections by parent entity position

### ISSUE THREAD

**Issue by madsciencetist** [MindFreeze/ha-sankey-chart#201] opened 2024-05-24 22:21 UTC
It seems like connections are sorted by child order on the right but not by parent order on the left. Is there a way to prevent these connections from crossing, without changing entity order?

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/7854563/c2bd7bbb-f9bb-4d46-ab09-d8efa271f22a)

**Comment by MindFreeze** [comment] 2024-05-25 04:28
Currently, no. I have to add sorting of the connections before their coordinates are calculated.

**Comment by MindFreeze** [comment] 2024-07-22 08:33
@madsciencetist After staring at the code for a while, I can't figure out how this could happen. Connections are rendered from top to bottom and left to right.
Can you help me reproduce it with some minimal config?

**Comment by MindFreeze** [comment] 2024-08-16 15:04
Since I can't reproduce this anymore, I'm going to assume it is fixed and close it

**Closed by MindFreeze** 2024-08-16 15:04 UTC
Labels: bug

**Comment by madsciencetist** [comment] 2024-08-16 15:33
Ah sorry, forgot about your repro request. This is not a problem for me
right now and if it becomes one again I’ll reopen with a repro config.
